system:
  seed: 42
  device: auto
  num_workers: 16
  verbose: true
  log_level: INFO
data:
  input_dir: data/raw/
  output_dir: data/processed/
  file_format: auto
preprocessing:
  remove_nans: true
  detrend:
    enabled: true
    method: polynomial
    order: 3
    window_length: 51
  sigma_clip:
    enabled: true
    sigma: 3.0
    iterations: 3
    method: iterative
  normalize:
    enabled: true
    method: zscore
  fold:
    enabled: false
    period: null
    epoch: 0.0
  bin:
    enabled: false
    bin_size: 0.01
    method: weighted
  quality_mask:
    enabled: true
    mad_threshold: 10.0
  min_points: 10
features:
  tier: comprehensive
  custom_features: []
  parallel: true
  cache_enabled: true
  fast:
    timeout: 1.0
  standard:
    timeout: 5.0
  comprehensive:
    timeout: 30.0
    n_jobs: -1
model:
  type: siamese
  architecture:
    hidden_dims:
    - 256
    - 128
    - 64
    embedding_dim: 32
    dropout_rate: 0.3
    activation: relu
training:
  epochs: 200
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 1.0e-05
  optimizer: adam
  margin: 1.0
  scheduler:
    enabled: true
    patience: 5
    factor: 0.5
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0001
  pairs:
    method: balanced
    pairs_per_sample: 5
    positive_ratio: 0.5
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  visualizations:
  - confusion_matrix
  - roc_curve
  - embedding
  save_predictions: true
  distance_threshold: 0.5
output:
  save_plots: true
  save_features: true
  save_models: true
  format: csv
  compression: null
  models_dir: outputs/models/
  logs_dir: outputs/logs/
  results_dir: outputs/results/
  plots_dir: outputs/plots/
